#!/bin/sh

export HOME=/config
export TMPDIR=/tmp
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

. /etc/default/plexmediaserver
export PLEX_MEDIA_SERVER_USER=user
export PLEX_MEDIA_SERVER_HOME=/usr/lib/plexmediaserver
export LD_LIBRARY_PATH="$PLEX_MEDIA_SERVER_HOME"
export PLEX_MEDIA_SERVER_TMPDIR="$TMPDIR"
export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="$HOME"

exec "$PLEX_MEDIA_SERVER_HOME/Plex Media Server"
