#!/bin/sh
set -e

[ -n "$PUID" ] || PUID=0
[ -n "$PGID" ] || PGID=0

mkdir -p /cache
usermod -o -u $PUID user
groupmod -o -g $PGID user
chown -R $PUID:$PGID /cache

exec su -pc /subliminal_watchdog.py user
