#!/bin/sh
set -e

# set defaults
PUID=${PUID:-1000}
PGID=${PGID:-1000}

mkdir -p /cache
usermod -o -u $PUID user
groupmod -o -g $PGID user
chown -R $PUID:$PGID /cache

exec su -pc /subliminal_watchdog.py user
