version: '3.1'

services:
    db:
        image: mysql:8
        restart: always
        cap_add:
            - SYS_NICE
        networks:
            - web
        volumes:
            - /mnt/data/docker/nextcloud/db:/var/lib/mysql
            - /root/secrets/nextcloud-db-root-passwd:/run/secrets/nextcloud-db-root-passwd:ro
        env_file:
            - ../common.env
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/nextcloud-db-root-passwd
    app:
        image: nextcloud:23
        restart: always
        networks:
            - web
        links:
            - db
        volumes:
            - /mnt/data/docker/nextcloud/app:/var/www/html
        env_file:
            - ../common.env
        labels:
            traefik.enable: true
            traefik.frontend.rule: Host:nc.example.com

networks:
    web:
        external: true
