version: '3.1'

services:
    db:
        image: postgres:12
        restart: always
        networks:
            - web
        volumes:
            - /mnt/data/docker/nextcloud/db:/var/lib/postgresql/data
            - /root/secrets/nextcloud-db-passwd:/run/secrets/nextcloud-db-passwd:ro
        env_file:
            - ../common.env
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/nextcloud-db-passwd
    app:
        image: nextcloud:19
        restart: always
        networks:
            - web
        links:
            - db
        volumes:
            - /mnt/data/docker/nextcloud/app:/var/www/html
        env_file:
            - ../common.env
        labels:
            traefik.enable: true
            traefik.frontend.rule: Host:nc.example.com

networks:
    web:
        external: true
