#!/bin/sh

mkdir -p /config/data
touch /config/CouchPotato.cfg

# set defaults
PUID=${PUID:-1000}
PGID=${PGID:-1000}

# fix /config permissions
usermod -o -u $PUID user
groupmod -o -g $PGID user
chown -R $PUID:$PGID /config

# start it
exec su -pc /start user
