#!/bin/sh

# set defaults
PUID=${PUID:-1000}
PGID=${PGID:-1000}

# fix permissions
usermod -o -u $PUID http
groupmod -o -g $PGID http
mkdir -p /etc/httpd/var /etc/httpd/logs /run/httpd
chown -R $PUID:$PGID /etc/httpd/var /etc/httpd/logs /run/httpd

# start it
exec supervisord -c /etc/supervisord.conf -n
