#!/bin/bash

is_true() {
    echo "$1" | grep -iqE '^[[:blank:]]*(y|yes|t|true|1)[[:blank:]]*$'
}

USE_SSL=${USE_SSL:-false}
ONLY_SSL=${ONLY_SSL:-false}
HTPASSWD_PATH="${HTPASSWD_PATH:-/config/.htpasswd}"
DHPARAM_PATH="${DHPARAM_PATH:-/config/dhparam.pem}"
CERT_PATH="${CERT_PATH:-/config/cert.pem}"
KEY_PATH="${KEY_PATH:-/config/key.pem}"

extra_args=()
is_true "$USE_SSL" && extra_args+=("-DUSE_SSL")
is_true "$ONLY_SSL" && extra_args+=("-DONLY_SSL")
[[ -f "$HTPASSWD_PATH" ]] && extra_args+=("-DHTPASSWD_PATH=$HTPASSWD_PATH")
[[ -f "$DHPARAM_PATH" ]] && extra_args+=("-DDHPARAM_PATH=$DHPARAM_PATH")
[[ -f "$CERT_PATH" ]] && extra_args+=("-DCERT_PATH=$CERT_PATH")
[[ -f "$KEY_PATH" ]] && extra_args+=("-DKEY_PATH=$KEY_PATH")

unset USE_SSL
unset ONLY_SSL
unset HTPASSWD_PATH
unset DHPARAM_PATH
unset CERT_PATH
unset KEY_PATH

exec httpd -k start -DFOREGROUND "${extra_args[@]}"
