#!/bin/bash

is_true() {
    echo "$1" | grep -iqE '^[[:blank:]]*(y|yes|t|true|1)[[:blank:]]*$'
}

add_var() {
    echo -n "Define '$1'" >> /tmp/httpd-vars.conf
    [[ -n "$2" ]] && echo -n " '$2'" >> /tmp/httpd-vars.conf
    echo >> /tmp/httpd-vars.conf
}

rm -f /tmp/httpd-vars.conf
touch /tmp/httpd-vars.conf

# fix permissions
mkdir -p /etc/httpd/var /etc/httpd/logs /run/httpd
chown -R http:http /etc/httpd/var /etc/httpd/logs /run/httpd

# set variables
USE_SSL=${USE_SSL:-false}
ONLY_SSL=${ONLY_SSL:-false}
HTPASSWD_PATH="${HTPASSWD_PATH:-/config/htpasswd}"
DHPARAM_PATH="${DHPARAM_PATH:-/config/dhparam.pem}"
CERT_PATH="${CERT_PATH:-/config/cert.pem}"
KEY_PATH="${KEY_PATH:-/config/key.pem}"

add_var FOREGROUND
is_true "$USE_SSL" && add_var USE_SSL
is_true "$ONLY_SSL" && add_var ONLY_SSL
[[ -f "$HTPASSWD_PATH" ]] && add_var HTPASSWD_PATH "$HTPASSWD_PATH"
[[ -f "$DHPARAM_PATH" ]] && add_var DHPARAM_PATH "$DHPARAM_PATH"
[[ -f "$CERT_PATH" ]] && add_var CERT_PATH "$CERT_PATH"
[[ -f "$KEY_PATH" ]] && add_var KEY_PATH "$KEY_PATH"

unset USE_SSL
unset ONLY_SSL
unset HTPASSWD_PATH
unset DHPARAM_PATH
unset CERT_PATH
unset KEY_PATH

# start server
exec httpd -k start
