#!/bin/sh

# set defaults
PUID=${PUID:-1000}
PGID=${PGID:-1000}

# fix permissions
usermod -o -u $PUID user
groupmod -o -g $PGID user
chown -R $PUID:$PGID /config

# start it
exec supervisord -c /etc/supervisor/supervisord.conf -n
