#!/bin/sh

# set defaults
PUID=${PUID:-1000}
PGID=${PGID:-1000}

# fix permissions
usermod -o -u $PUID user
groupmod -o -g $PGID user
chown -R $PUID:$PGID /config

# fix environment variables
export USER=user
export HOME=/config

# fix TLS issue in Mono 5.0.0
export MONO_TLS_PROVIDER=legacy

# start it
exec supervisord -c /etc/supervisord.conf -n
