#!/bin/bash

die() {
    [[ -n "$@" ]] && echo "$@"
    exit 1
}

extip() {
    dig +short myip.opendns.com @resolver1.opendns.com 2> /dev/null
}

# from http://stackoverflow.com/a/32144661
is_privileged() {
    ip link add dummy0 type dummy > /dev/null 2>&1 || return 1
    ip link delete dummy0 > /dev/null 2>&1
    return 0
}

is_privileged || die "This container needs to be run with '--privileged' option"
[[ -z "$IODINE_TOP_DOMAIN" ]] && die "IODINE_TOP_DOMAIN environment variable is mandatory"
[[ -z "$IODINE_PASSWORD" ]] && die "IODINE_PASSWORD environment variable is mandatory"

IODINE_TUN_IP=${IODINE_TUN_IP:-172.18.42.1/24}
IODINE_EXT_IP=${IODINE_EXT_IP:-$(extip)}
IODINE_PORT=${IODINE_PORT:-53}
IODINE_BIND_ADDRESS=${IODINE_BIND_ADDRESS:-0.0.0.0}

[[ -z "$IODINE_EXT_IP" ]] && die "Failed to get the external IP"

[[ ! -d /dev/net ]] && mkdir -p /dev/net
[[ ! -c /dev/net/tun ]] && mknod /dev/net/tun c 0xa 0xc8

echo 1 > /proc/sys/net/ipv4/conf/eth0/forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -w -t nat -I POSTROUTING -o eth0 -s $IODINE_TUN_IP -j MASQUERADE

iodined -f -c -l $IODINE_BIND_ADDRESS -n $IODINE_EXT_IP \
    -p $IODINE_PORT -P "$IODINE_PASSWORD" -u nobody \
    $IODINE_TUN_IP $IODINE_TOP_DOMAIN
