#!/bin/bash

die() {
    [[ -n "$@" ]] && echo "$@"
    exit 1
}

extip() {
    dig +short myip.opendns.com @resolver1.opendns.com 2> /dev/null
}

# from http://stackoverflow.com/a/32144661
is_privileged() {
    ip link add dummy0 type dummy > /dev/null 2>&1 || return 1
    ip link delete dummy0 > /dev/null 2>&1
    return 0
}

is_privileged || die "This container needs to be run with '--privileged' option"
[[ -z "$IODINED_TOP_DOMAIN" ]] && die "IODINED_TOP_DOMAIN environment variable is mandatory"
[[ -z "$IODINED_PASSWORD" ]] && die "IODINED_PASSWORD environment variable is mandatory"

IODINED_TUN_IP=${IODINED_TUN_IP:-10.0.0.1/24}
IODINED_EXT_IP=${IODINED_EXT_IP:-$(extip)}

[[ -z "$IODINED_EXT_IP" ]] && die "Failed to get the external IP"

[[ ! -d /dev/net ]] && mkdir -p /dev/net
[[ ! -c /dev/net/tun ]] && mknod /dev/net/tun c 0xa 0xc8

echo 1 > /proc/sys/net/ipv4/conf/eth0/forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -w -t nat -I POSTROUTING -o eth0 -s $IODINED_TUN_IP -j MASQUERADE

exec iodined -f -c -n $IODINED_EXT_IP -P "$IODINED_PASSWORD" -u nobody \
    $IODINED_TUN_IP $IODINED_TOP_DOMAIN
