#!/bin/sh

# backward complatible
[ -n "$NGINX_UID" ] && PUID=${PUID:-$NGINX_UID}
[ -n "$NGINX_GID" ] && PGID=${PGID:-$NGINX_GID}
PGID=${PGID:-$PUID}

# set new UID/GID
[ -n "$PUID" ] && usermod -o -u $PUID nginx
[ -n "$PGID" ] && groupmod -o -g $PGID nginx

# start it
exec nginx -g "daemon off;"
