#!/bin/sh

# set defaults
PUID=${PUID:-1000}
PGID=${PGID:-1000}

# init config
mkdir -p /config/data
if [ ! -e /config/nzbget.conf ]; then
    cp /opt/nzbget/nzbget.conf /config
    sed -i 's|^MainDir=.*|MainDir=/config/data|' /config/nzbget.conf
    sed -i 's|^DestDir=.*|DestDir=/data|' /config/nzbget.conf
    sed -i 's|^ControlPassword=.*$|ControlPassword=|' /config/nzbget.conf
fi

# fix permissions
usermod -o -u $PUID user
groupmod -o -g $PGID user
chown -R $PUID:$PGID /config

# start it
exec su -pc /start user
