#!/bin/sh

die() {
    echo "$@"
    exit 1
}

fix_btrfs() {
    [ -z "$1" ] && return
    if df -T "$1" | awk '{print $2}' | grep -q btrfs; then
        echo "Btrfs detected, disabling CoW on '$1'"
        chattr -R +C "$1"
    fi
}

mkdir_if_needed() {
    [ -z "$1" ] && return
    [ -d "$1" ] && return
    [ -e "$1" ] && die "'$1' must be a directory"
    mkdir -p "$1"
    chown $PUID:$PGID "$1"
}

# set defaults
PUID=${PUID:-0}
PGID=${PGID:-0}
export DOWNLOAD_DIR="${DOWNLOAD_DIR:-/data}"

# fix /config permissions
usermod -o -u $PUID user
groupmod -o -g $PGID user
chown -R $PUID:$PGID /config

# create directories if needed
mkdir_if_needed "$DOWNLOAD_DIR"
mkdir_if_needed "$INCOMPLETE_DIR"

# if the fs of the download directories is btrfs then
# we need to disable CoW, otherwise we can have corrupted files
fix_btrfs "$DOWNLOAD_DIR"
fix_btrfs "$INCOMPLETE_DIR"

# start it
exec su -pc /start user
